# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.6.4
    restart: always
    environment:
      environment:
      MARIADB_DATABASE: challengeBackend
      MARIADB_ROOT_PASSWORD: root
    ports:
    - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080